.pullapprove.yml

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

pullapprove: Have the web team gating all PRs

---

css/main.css
index.html

Added emma form, new CSS, GA script

---

index.html

New News link, general text updates

---

index.html

Fixing social icons, adding new verbiage

---

index.html

Signed-off-by: Jonathan Bryce <jbryce@jbryce.com>

Add link to Press Release

---

index.html

Signed-off-by: Jonathan Bryce <jbryce@jbryce.com>

Adding registered trademark for Intel reference

---

index.html

Add hyperlinks to the contributing Clear Containers and runV projects.
Fixes #16.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

docs: Make Clear Containers and runV links

---

index.html

Added United Stack and Dell

---

css/main.css

Signed-off-by: beluiba <belenibanezm@gmail.com>

column view in links fixed

---

css/main.css
index.html

Fixed links to Hyper V and clear containers, fixed overlay

---

index.html

Updated press release regression

---

index.html

Added Emma email signup to Kata site

---

index.html
thankyou.html

* Adding thankyou.html
* Removing popup code
* Adding in-page script

Moving Emma form to -in page

---

thankyou.html

Spelling correction

---

thankyou.html

Linked logo back to Kata Homepage

---

index.html

Update slack channel URL to point to invite URL

---

index.html

Updating links in orange events bar

---

index.html

* Fixed a missing <li> tag
* Added in 3 missing alt atributes on img tags
* Removed one duplicate alt attribute

Fixes some issues raised in #43

---

CONTRIBUTING.md

Fixes : #45
See : kata-containers/community#5
Signed-off-by: Yash Jain <ydjainopensource@gmail.com>

 Docs : Add minimal contribution guidelines

---

blog_landing.html
blog_post.html
css/main.css
index.html
page.html
templates/base.html
templates/blog_landing.html
templates/blog_post.html
templates/index.html
templates/page.html
templates/post_detail.html

This PR includes the Django templates used for the new CMS, and all the CSS and JS currently live in the production site.

CSS tweaks and Django templates

---

site/.vuepress/components/bar.vue

Fix for broken p tag

---

site/.vuepress/components/bar.vue

- She didn't include the protocol
- We missed it during review.

Fixing Allison Price's terrible mistake

---

site/.vuepress/public/admin/config.yml

Completes migration to kata-containers/www.katacontainers.io repo.

Updates NetlifyCMS backend repo config.

---

site/.vuepress/components/HomeContent.vue

Update slack invite URL to working link

---

site/.vuepress/components/HomeAnnouncement.vue
site/.vuepress/components/HomeContent.vue
site/index.md

- Update to 1.9 release
- Add call out for Survey under "Get Involved"
- Update announcement box for Survey

Homepage Updates

---

site/index.md

- Change release # from 1.9 to 1.10 in site header

Update release from 1.9 to 1.10

---

src/pages/software/index.md

docs: add link to installation documents

---

src/pages/software/index.md

docs: fix typos for arch and platform

---

src/content/pages.json

- Closes #97
Signed-off-by: Michael Vincerra <michael.vincerra@intel.com>

subsystem: Replace URL of Blog in nav w/ URL for medium.com

---

static/admin/config.yml

Signed-off-by: Gabriel Horacio Cutrini <gabriel.cutrini@gmail.com>

Makes NetlifyCMS use Netlify provided auth component.

---

netlify.toml

Adding force and status to redirect rules

Change in redirect rules for /blog

---

src/components/Footer.js
src/pages/community/index.md
src/pages/index.md
src/pages/learn/index.md
src/pages/supporters/index.md

[DO NOT MERGE] Changing out general openstack branding

---

gatsby-config.js
src/components/Subscribe.js
src/style/modules/_search.scss

* Replaces the form with a button that opens a popup to sign up to news, so the user isn't redirected and stays on the page.
Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>

change subscription form for link button

---

src/content/footer-nav.json
src/pages/learn/index.md

Update remaining content to refer to the current 2.x releases URL.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

links: Use 2.x releases URL

---

src/templates/index-page.js
src/templates/learn-page.js
src/templates/software-page.js
src/templates/supporters-page.js

* Catch error on CMS preview pages when the user create a new element. Fix index, learn, sofware and supporters pages
Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>

Catch error on CMS adding elements

---

src/content/pages.json
src/pages/use-cases/index.md
src/templates/use-cases-page.js

- Creates a new page to feature simple case studies
- Adds a link named "Users" to navbar

Add Users Page

---

src/pages/community/index.md

Update the meeting URL to 2022

update architecture committee meeting address for 2022

---

src/pages/index.md

Fixes: #188
Signed-off-by: bin liu <bin@hyper.sh>

update architecture committee meeting

---

src/pages/docs/index.md

refer to https://github.com/kata-containers/kata-containers/issues/6015
Signed-off-by: bin liu <bin@hyper.sh>

Fix broken link for how to run kata with Kubernetes

---

src/pages/use-cases/index.md

Edited the link to the Kata Containers survey to point to the new Formstack form.

Survey link update for index.md

---

src/pages/blog/kata-containers-project-updates-q4-2024.md

This patch adds a new blog post to share project updates for Q4, 2024.

Add Project Updates blog post

---

src/pages/blog/switchboard-oracles-and-kata-containers.md

This PR is to add a quick technical blog article to explain the integration between our Switchboard Oracles and Kata Containers.
links:
https://switchboard.xyz
https://docs.switchboard.xyz/switchboard-protocol/running-a-switchboard-oracle

Switchboard Oracle: add blog about Kata-containers + Switchboard Oracles

---

src/content/footer-nav.json

This patch adds a link to the vulnerability reporting process in the Kata documentation on GH.

Update website footer
