- CODE_OF_CONDUCT.md
Adding in a Code of Conduct template that references the overall OSF Community Code of Conduct.
Signed-off-by: Jonathan Bryce <jbryce@jbryce.com>
> Add Code of Conduct template

- index.html
A link was included for the developer focused #kata-dev
channel, but not the more user focused #kata-general.
This adds explicit links for both to the Communications
list.
Closes #35
Signed-off-by: Sean McGinnis <sean.mcginnis@huawei.com>
> Add link for #kata-general IRC channel

- package-lock.json
By reinstalling vuepress@0.14.11, we upgrade its dependencies, fixing most vulnerabilities listed in npm audit and the security alerts listed by github.
> Reinstalls vuepress to upgrade dependencies.

- site/community/index.md
- Switching out the bitly since the origin expired.
> Renaming bitly URL

- static/admin/config.yml
Instead of having all CMS save or edits be committed directly into repo, editorial workflow translates CMS actions into common git commands:
When you:
- Save a draft -> it commits to a new branch (named according to the pattern cms/collectionName/entrySlug), and opens a pull request.
- Edit draft -> it pushes another commit to the draft branch/pull request.
- Approve and publish draft -> it merges pull request and deletes branch.
> Restores Netlify CMS editorial workflow.

- src/pages/index.md
NEMU is no longer available. Cloud Hypervisor should be the one listed as
supported by Kata.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
> index.md: Add Cloud Hypervisor and remove NEMU

- src/content/footer-nav.json
- src/pages/community/index.md
Freenode is no longer the home of the kata-containers IRC channels.
Following the announcement on our mailing list, we've moved to OFTC:
http://lists.katacontainers.io/pipermail/kata-dev/2021-May/001938.html
Fixes: #149
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
> IRC: Point to OFTC channels

- src/pages/docs/index.md
This updates to the proper url for the contribution guide.
Fixes: #151
Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>
> docs: Update url for contribution guide

- static/admin/config.yml
It seems that the only required change is to switch the backend branch
from `master` to `main`, and theoretically we should be good to go to
fully switch to using `main` on *all* repos which are part of the
kata-containers organization.
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
> config: Use `main` branch instead of `master`

- src/pages/docs/index.md
This was previously a single markdown file.
It was updated to a directory in:
https://github.com/kata-containers/kata-containers/commit/6f9efb4043f38a384d4f07c5e545a3377c0759ff#diff-20c51aad7f36c9befb2e1ebef90660ea47b2a30e84c56235baea581c5001b8a8
Signed-off-by: Agam Dua <agam_dua@apple.com>
> Fixed: link to architecture docs.

- src/content/top-bar.json
Replacing the OpenInfra Live Keynotes video announcement with a promo for the OpenInfra Summit in Berlin
> top banner Summit promo

- src/pages/index.md
The slack link in the community page has been updated, but the index page was forgotten.
Signed-off-by: liubin <liubin0329@gmail.com>
> update slack link in index page

- src/pages/index.md
The commit ca54f2871be98bf7debff182d0427ad648cef44d introduces wrong etherpad and slack links.
This reverts commit ca54f2871be98bf7debff182d0427ad648cef44d.
> Revert "Automatically generated. Merged on Netlify CMS"

- src/content/blog-config.json
- src/pages/blog/index.js
This patch adds a link to the new description in the Kata Containers docs about how to contribute a new blog post to the website.
> Add link to blog submission guidelines

- src/pages/blog/kata-containers-3-5-0-release-overview.md
This patch adds a new blog post to provide highlights of the latest, 3.5.0 release of Kata Containers.
> Add a release 3.5.0 overview blog post

- src/pages/blog/kata-containers-for-ai-workloads.md
This commit adds a new blog post to the Kata Containers blog to capture the projects general applicability to the AI tools and  applications, and with that highlighting the projct's relevance and importance in the space.
> Add Kata AI blog post

- src/pages/docs/index.md
Add two spaces at the end of line as a line break to user guide section.
Current docs page:
> Fix line break in docs page

- src/pages/community/index.md
The Kata community has rescheduled the AC meeting series, this patch adds the new time to the Community tab on the website.
> Update AC meeting time on the Community tab

- src/pages/community/index.md
This patch adds the new Bluesky social media account to the Community page on the website, to increase the visibility of the new account.
> Add Bluesky account to Community page

- src/pages/community/index.md
The COmmunity page of the website has a link to the install documentation. The old link pointed to a 'documentation' repo, which is now archived. This patch adds the link to the current docs.
> Updating outdated link to install docs

- src/pages/use-cases/index.md
This patch adds Northflank's case study to the Users page on the Kata Containers website. It points to a detailed case study on the Kata blog for further details readers can check out,
> Add Northflank to Users page

- src/content/top-bar.json
This patch updates the website banner to point to the upcoming price increase for the OpenInfra Summit Europe event.
> Update website banner
